exclude: ['README.md', 'Rakefile']
markdown: rdiscount
permalink: ':title'
pygments: true
safe: false

url: http://localhost:4000
title: KosmicLabs | Thinking Beyond the Web
description: "A collection of unpolished ideas and thoughts in the realms of front-end development, web design, entrepreneurship and startups."
gosquared_key: null

paginate: 5
paginate_path: '/page:num'

sass: 
  style: nested
  deploy_style: nested
  compile_in_place: false